version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/var/www/express-typescript:delegated
    working_dir: /var/www/express-typescript
    command: npm run start

  db:
    image: mariadb:10.3
    ports:
      - 13306:3306
    volumes:
      - ./docker/db-store:/var/lib/mysql
      - ./docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: database_dev
      MYSQL_USER: root
      TZ: Asia/Tokyo

  db-testing:
    image: mariadb:10.3
    ports:
      - 13307:3306
    volumes:
      - ./docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: database_dev
      MYSQL_USER: root
      TZ: Asia/Tokyo
